use sqldb;
select database();
select * from usertbl;
select * from usertbl where name = '김경호' or name = '김범수';
select * from usertbl where addr = '서울' and name = '이승기';
select * from usertbl where birthYear >= 1970 and height >= 182;
select userID, name from usertbl where birthYear >= 1970 and height >= 182;
select name, height from usertbl where height >= 180 and height <= 183;
select name, addr from usertbl where height between 180 and 183;
select name, addr from usertbl where addr = '경남' or addr = '전남' or addr = '경북';
select name, addr from usertbl where addr in('경남','전남','경북');
select name, height from usertbl where name like '김%';
select name, height from usertbl where name like '_종신';
select name, height from usertbl where height > 177;
select name, height from usertbl where height > (select height from usertbl where name = '김경호');
select name, height from usertbl where height >= (select height from usertbl where addr = '경남');
select name, height from usertbl where height >= any (select height from usertbl where addr = '경남');
select name, height from usertbl where height >= all (select height from usertbl where addr = '경남');
select name, height from usertbl where height = any (select height from usertbl where addr = '경남');
select name, height from usertbl where height in ( select height from usertbl where addr = '경남');
select name, mDate from usertbl order by mDate;
select name, mDate from usertbl order by mDate DESC;
select name, height from usertbl order by height DESC, name ASC;
select addr from usertbl;
select addr from usertbl order by addr;
select distinct addr from usertbl;
use employees;
select emp_no, hire_date from employees order by hire_date asc;
select emp_no, hire_date from employees order by hire_date asc limit 5;
select emp_no, hire_date from employees order by hire_date asc limit 0,5;
use sqldb;
create table buytbl2 (select * from buytbl);
select * from buytbl2;
create table buytbl3 (select userID, prodName from buytbl);
select * from buytbl3;
select userID, amount from buytbl order by userID;
select userID, sum(amount) from buytbl group by userID;
select userID AS '사용자 아이디', sum(amount) AS '총 구매 개수' from buytbl group by userID;
select avg(amount) as '평귝 구매 개수' from buytbl;